### ISSUE TITLE
createqsobjects KeyError: 'AWSAccountID'

### ISSUE THREAD

**Issue by tejsheth** [aws-samples/amazon-security-lake-generative-ai#2]
After CDK deploy getting error when QS dashboard generation script gets executed

Traceback (most recent call last):
  File "/Users/tsheth/Code/amazon-security-lake-quicksight/cdk-lakeformation-permissions/source/../../scripts/createqsobjects.py", line 16, in <module>
    aws_account_id = parameters['context']['AWSAccountID']
KeyError: 'AWSAccountID'
Finished QuickSight Generate Dashboards

**Comment by tamg-aws** [comment]
@tejsheth - I believe you meant to open this issue against https://github.com/aws-samples/amazon-security-lake-quicksight? 

I see your issue is related to https://github.com/aws-samples/amazon-security-lake-quicksight/blob/24304e70fa123ea9dc2444062a8c783334ffd0a1/scripts/createqsobjects.py#L16. Please open the issue against the other project to make sure it gets addressed.
